language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.4
  - 1.8.0
  - 1.9.1
otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 22.0
dist: trusty

matrix:
  exclude:
  - elixir: 1.4.5
    otp_release: 20.3
  - elixir: 1.4.5
    otp_release: 22.0
  - elixir: 1.5.3
    otp_release: 20.3
  - elixir: 1.5.3
    otp_release: 22.0
  - elixir: 1.6.6
    otp_release: 20.3
  - elixir: 1.6.6
    otp_release: 22.0
  - elixir: 1.7.4
    otp_release: 18.3
  - elixir: 1.7.4
    otp_release: 22.0
  - elixir: 1.8.0
    otp_release: 18.3
  - elixir: 1.8.0
    otp_release: 19.3
  - elixir: 1.9.1
    otp_release: 18.3
  - elixir: 1.9.1
    otp_release: 19.3


script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
